name: add_package.yml
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AgentForge
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet build --configuration Release
      - name: Package
        run: >
            dotnet pack --no-restore --no-build --configuration Release
            -p:PackageVersion=${{ github.ref_name }} --output .
      - name: Publish
        run: >
          dotnet nuget push AgentForge.${{ github.ref_name }}.nupkg 
          -s https://nuget.pkg.github.com/tomasantunes/index.json 
          -k ${{ secrets.GIT_TOKEN }}