name: 'Publish Agent Forge to NuGet'
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./AgentForge
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Check Tags
        run: echo ${{github.ref_name}}
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet build --configuration Release
      - name: Authenticate to GitHub Packages
        run: >
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GIT_TOKEN }}
          --store-password-in-clear-text
          --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      - name: Package
        run: >
            dotnet pack --no-restore --no-build --configuration Release
            -p:PackageVersion=${{ github.ref_name }} --output .
      - name: Publish
        run: dotnet nuget push AgentForge.${{ github.ref_name }}.nupkg -s github --api-key ${{ secrets.GIT_TOKEN }}