name: 'Publish Agent Forge to NuGet'
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    defaults:
      run:
        working-directory: ./AgentForge
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Check Tags
        run: echo ${{github.ref_name}}
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet build --configuration Release
      - name: Package
        run: >
            dotnet pack --no-restore --no-build --configuration Release
            -p:PackageVersion=${{ github.ref_name }} --output .
      - name: Publish
        run: >
          dotnet nuget push AgentForge.${{ github.ref_name }}.nupkg 
          --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
          --skip-duplicate